spring.application.name=task-management
spring.datasource.url=jdbc:postgresql://localhost:5432/task_management
spring.datasource.username=task_app
spring.datasource.password=task_app_password

jwt.secret = ${JWT_SECRET}
jwt.expiration = 3600000

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG

#export JWT_SECRET='D6dXPCyxYUnka6be/W2zXjXlp0DH5uKGW9a7ZkM7KrY='