spring.application.name=task-management
spring.datasource.url=jdbc:postgresql://localhost:5432/task_management
spring.datasource.username=task_app
spring.datasource.password=task_app_password

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG